services:
  app:
    depends_on:
      - rabbitmq
    build: 
      context: .
      target: development
      dockerfile: Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
        DEV: ${DEV:-false}
        POETRY_VERSION: ${POETRY_VERSION:-1.8.4}
    env_file:
      - .env
    volumes:
      - .:/app
    tty: true
    stdin_open: true
  rabbitmq:
    image: 'rabbitmq:4.0-management'
    environment:
      - 'RABBITMQ_DEFAULT_USER=admin'
      - 'RABBITMQ_DEFAULT_PASS=secret'
    ports:
      - '5672:5672'
      - '15672:15672'
