services:
  app:
    user: "${UID}:${GID}"
    hostname: app.local
    networks:
      default:
        aliases: [ "app" ]
    ports:
      - "127.0.0.1:8000:8000"
    build: 
      context: .
      target: development
      dockerfile: Dockerfile
      args:
        UID: ${UID:-1000}
        GID: ${GID:-1000}
        DEV: ${DEV:-false}
        POETRY_VERSION: ${POETRY_VERSION:-1.8.4}
    env_file:
      - .env
    environment:
      - ROCKET_SECRET_KEY="rocket_secret_key"
    volumes:
      - .:/app
      - '/Users/gkostin/rocket/db:/app/rocket/db/'
    tty: true
    stdin_open: true
networks:
  default:
