FROM alpine:latest

ARG PB_VERSION=0.25.8

RUN apk add --no-cache \
    unzip \
    ca-certificates

# download and unzip PocketBase
WORKDIR /pb
ADD https://github.com/pocketbase/pocketbase/releases/download/v${PB_VERSION}/pocketbase_${PB_VERSION}_linux_amd64.zip /tmp/pb.zip
RUN unzip /tmp/pb.zip -d /pb/
RUN rm /tmp/pb.zip

# Copy the user setup script 
COPY pb_user_setup.sh /pb/pb_user_setup.sh

# Ensure the script is executable
RUN chmod +x /pb/pb_user_setup.sh

EXPOSE 8080
