version: '3.8'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  publisher:
    build:
      context: ./app/publisher
    depends_on:
      - redis

  subscriber:
    build:
      context: ./app/subscriber
    depends_on:
      - redis
