---
name: Continuous Integration

on:
  workflow_dispatch:
  push:
  pull_request:
    branches:
      - 'main'

jobs:
  ci:
    if: ${{ github.event_name == 'push' || github.event.pull_request.merged == true }}

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up fileset-data volume
        run: |
          docker volume create dor-py_fileset-data
          docker run --rm -v dor-py_fileset-data:/data alpine sh -c "mkdir -p /data/filesets && chown -R 1000:1000 /data && chmod -R 775 /data"
      - name: Run tests
        run: |
          ./init.sh
          docker compose run --rm app poetry run pytest
