---
  name: Build and release CLI package

  on:
    workflow_dispatch:

  env:
    UUID: ${{ github.run_id }}

  jobs:
    build:
      runs-on: ubuntu-latest
      permissions:
        contents: read
        packages: write
      steps:
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v2

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3

        - name: Login to GitHub Container Registry
          uses: docker/login-action@v3
          with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

        - name: Checkout
          uses: actions/checkout@v4

        - name: Build CLI package
          uses: docker/build-push-action@v5
          with:
            context: .
            push: false
            load: true
            tags: 'mlibrary/dor-cli:latest'
            file: Dockerfile
            target: cli-build

        - name: Publish CLI package with Poetry
          run: |
            docker run --rm \
            -e POETRY_REPOSITORIES_DOR_URL="${{ vars.POETRY_REPOSITORIES_DOR_URL }}" \
            -e POETRY_HTTP_BASIC_DOR_USERNAME="${{ vars.POETRY_HTTP_BASIC_DOR_USERNAME }}" \
            -e POETRY_HTTP_BASIC_DOR_PASSWORD="${{ secrets.POETRY_HTTP_BASIC_DOR_PASSWORD }}" \
            mlibrary/dor-cli poetry publish -r dor
